server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices3
    username: root
    password: Mush@r@f4564
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: RATING-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service url:
      defaultZone: http://localhost:8761/eureka